{"name": "test_xfail", "status": "skipped", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "self = <test_add_api.TestInTheaters object at 0x7fcda5eeb2e0>\n\n    @pytest.mark.xfail\n    def test_xfail(self):\n        \"\"\"\n        Indicate that you expect it to fail\n        这条用例失败时，测试结果被标记为xfail（expected to fail），并且不打印错误信息。\n        这条用例执行成功时，测试结果被标记为xpassed（unexpectedly passing）\n        \"\"\"\n>       assert 1 == 2\nE       assert 1 == 2\n\ntests/test_add_api.py:49: AssertionError"}, "description": "\n        Indicate that you expect it to fail\n        这条用例失败时，测试结果被标记为xfail（expected to fail），并且不打印错误信息。\n        这条用例执行成功时，测试结果被标记为xpassed（unexpectedly passing）\n        ", "start": 1594995983898, "stop": 1594995983898, "uuid": "e8c779d2-2b04-4364-a3e9-8db8f2d1e53e", "historyId": "1d5187a24a55dbe6c4ea0e6d557bdaa2", "testCaseId": "8750ee287e021923dc55c3ec6db76014", "fullName": "tests.test_add_api.TestInTheaters#test_xfail", "labels": [{"name": "feature", "value": "API密钥功能"}, {"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_add_api"}, {"name": "subSuite", "value": "TestInTheaters"}, {"name": "host", "value": "shawn.local"}, {"name": "thread", "value": "3595-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_add_api"}]}